#!/usr/bin/env sh
#
# Copyright (c) 2023.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without modification, are not permitted.
#

. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit
npx --no-install commitlint --edit $1
